version: '3.9'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tuank1994
      POSTGRES_DB: testdb
    networks:
      - nestjs-network

  test-database:
    image: postgres:15.0
    container_name: test-database
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tuank1994
      POSTGRES_DB: testdb
    networks:
      - nestjs-network

networks:
  nestjs-network:
